const NAME_ACTION = {
   GET_LIST_POST: 'GET_LIST_POST',
   GET_POST_DETAIL: 'GET_POST_DETAIL',
   POST_SUCCESSED: 'POST_SUCCESSED',
   POST_UNSUCCESSED: 'POST_UNSUCCESSED',
   CHANGE_PASSWORD: 'CHANGE_PASSWORD',
   CHANGE_NAME_AVAVATR: 'CHANGE_NAME_AVAVATR'
}

export default NAME_ACTION